#pragma once

#include "wintypes/primitive.h"

// from minwindef.h

//   for WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM

DECLARE_HANDLE(HKEY);
typedef HKEY *PHKEY;
DECLARE_HANDLE(HMETAFILE);
DECLARE_HANDLE(HINSTANCE);
typedef HINSTANCE HMODULE;      /* HMODULEs can be used in place of HINSTANCEs */
DECLARE_HANDLE(HRGN);
DECLARE_HANDLE(HRSRC);
DECLARE_HANDLE(HSPRITE);
DECLARE_HANDLE(HLSURF);
DECLARE_HANDLE(HSTR);
DECLARE_HANDLE(HTASK);
DECLARE_HANDLE(HWINSTA);
DECLARE_HANDLE(HKL);

typedef int HFILE;

typedef struct _FILETIME {
    DWORD dwLowDateTime;
    DWORD dwHighDateTime;
} FILETIME, *PFILETIME, *LPFILETIME;
#define _FILETIME_

// from windef.h

//   for WINAPI_PARTITION_APP | WINAPI_PARTITION_SYSTEM

DECLARE_HANDLE(HWND);
DECLARE_HANDLE(HHOOK);

DECLARE_HANDLE(HICON);
DECLARE_HANDLE(HWINEVENTHOOK);
DECLARE_HANDLE(HMONITOR);

typedef HICON HCURSOR;
typedef DWORD COLORREF, *PCOLORREF, *LPCOLORREF;

#if !defined(GDI_INTERNAL)
DECLARE_HANDLE(HGDIOBJ);
DECLARE_HANDLE(HBITMAP);
DECLARE_HANDLE(HBRUSH);
DECLARE_HANDLE(HDC);
DECLARE_HANDLE(HFONT);
DECLARE_HANDLE(HPALETTE);
DECLARE_HANDLE(HPEN);
#endif

#if !defined(WIN_INTERNAL)
DECLARE_HANDLE(HACCEL);
DECLARE_HANDLE(HMENU);
#endif

//   for WINAPI_PARTITION_DESKTOP

DECLARE_HANDLE(HEVENT);
DECLARE_HANDLE(HUMPD);
